version: "3.8"
services:
  db:
    container_name: firebase-auth-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: firebase
      POSTGRES_PASSWORD: firebase
      POSTGRES_DB: firebase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    container_name: firebase-auth-cache
    image: redis
    restart: no
    ports:
      - "6379:6379"

volumes:
  db-data:
