version: "3.8"
services:
  db:
    container_name: invite-system-db
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: invite_system
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    container_name: invite-system-redis
    image: redis
    restart: no
    ports:
      - "6379:6379"

volumes:
  db-data:
