export const countriesWithCodes = [
  {
    name_en: "Colombia",
    continent_en: "South America",
    capital_en: "Bogota",
    dial_code: "+57",
    code_2: "CO",
    code_3: "COL",
    tld: ".co",
    emoji: "🇨🇴",
    placeholder: "300 123 4567",
  },
  {
    name_en: "Mexico",
    continent_en: "North America",
    capital_en: "Mexico City",
    dial_code: "+52",
    code_2: "MX",
    code_3: "MEX",
    tld: ".mx",
    emoji: "🇲🇽",
    placeholder: "55 1234 5678",
  },
  {
    name_en: "United States",
    continent_en: "North America",
    capital_en: "Washington, D.C.",
    dial_code: "+1",
    code_2: "US",
    code_3: "USA",
    tld: ".us",
    emoji: "🇺🇸",
    placeholder: "(555) 123-4567",
  },
  {
    name_en: "Canada",
    continent_en: "North America",
    capital_en: "Ottawa",
    dial_code: "+1",
    code_2: "CA",
    code_3: "CAN",
    tld: ".ca",
    emoji: "🇨🇦",
    placeholder: "(555) 123-4567",
  },
  {
    name_en: "Brazil",
    continent_en: "South America",
    capital_en: "Brasília",
    dial_code: "+55",
    code_2: "BR",
    code_3: "BRA",
    tld: ".br",
    emoji: "🇧🇷",
    placeholder: "(11) 1234-5678",
  },
  {
    name_en: "Argentina",
    continent_en: "South America",
    capital_en: "Buenos Aires",
    dial_code: "+54",
    code_2: "AR",
    code_3: "ARG",
    tld: ".ar",
    emoji: "🇦🇷",
    placeholder: "11 1234-5678",
  },
  {
    name_en: "Chile",
    continent_en: "South America",
    capital_en: "Santiago",
    dial_code: "+56",
    code_2: "CL",
    code_3: "CHL",
    tld: ".cl",
    emoji: "🇨🇱",
    placeholder: "9 1234 5678",
  },
  {
    name_en: "Peru",
    continent_en: "South America",
    capital_en: "Lima",
    dial_code: "+51",
    code_2: "PE",
    code_3: "PER",
    tld: ".pe",
    emoji: "🇵🇪",
    placeholder: "912 345 678",
  },
  {
    name_en: "Ecuador",
    continent_en: "South America",
    capital_en: "Quito",
    dial_code: "+593",
    code_2: "EC",
    code_3: "ECU",
    tld: ".ec",
    emoji: "🇪🇨",
    placeholder: "099 123 4567",
  },
  {
    name_en: "Pakistan",
    continent_en: "Asia",
    capital_en: "Islamabad",
    dial_code: "+92",
    code_2: "PK",
    code_3: "PAK",
    tld: ".pk",
    emoji: "🇵🇰",
    placeholder: "300 1234567",
  },
  {
    name_en: "India",
    continent_en: "Asia",
    capital_en: "New Delhi",
    dial_code: "+91",
    code_2: "IN",
    code_3: "IND",
    tld: ".in",
    emoji: "🇮🇳",
    placeholder: "81234 56789",
  },
  {
    name_en: "Bangladesh",
    continent_en: "Asia",
    capital_en: "Dhaka",
    dial_code: "+880",
    code_2: "BD",
    code_3: "BGD",
    tld: ".bd",
    emoji: "🇧🇩",
    placeholder: "01812-345678",
  },
  {
    name_en: "Sri Lanka",
    continent_en: "Asia",
    capital_en: "Sri Jayawardenepura Kotte",
    dial_code: "+94",
    code_2: "LK",
    code_3: "LKA",
    tld: ".lk",
    emoji: "🇱🇰",
    placeholder: "071 123 4567",
  },
  {
    name_en: "Nepal",
    continent_en: "Asia",
    capital_en: "Kathmandu",
    dial_code: "+977",
    code_2: "NP",
    code_3: "NPL",
    tld: ".np",
    emoji: "🇳🇵",
    placeholder: "984-1234567",
  },
  {
    name_en: "Bhutan",
    continent_en: "Asia",
    capital_en: "Thimphu",
    dial_code: "+975",
    code_2: "BT",
    code_3: "BTN",
    tld: ".bt",
    emoji: "🇧🇹",
    placeholder: "1712 3456",
  },
  {
    name_en: "Maldives",
    continent_en: "Asia",
    capital_en: "Malé",
    dial_code: "+960",
    code_2: "MV",
    code_3: "MDV",
    tld: ".mv",
    emoji: "🇲🇻",
    placeholder: "771 2345",
  },
] as const satisfies ReadonlyArray<{
  name_en: string;
  continent_en: string;
  capital_en: string;
  dial_code: string;
  code_2: string;
  code_3: string;
  tld: string;
  emoji: string;
  placeholder: string;
}>;

export type CountryWithCode = (typeof countriesWithCodes)[number];
